name = "TazedCraft"
author = "JonnyB <me@jonnyb.name>"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d839a0bc1adb7c11cbae0b089fd7f3630ba7910543f579998d46f57c16dea0ef"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.2"]
