name = "TazedCraft"
author = "JonnyB <me@jonnyb.name>"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27cbba6d3447bc94650716e7ce95569e08d475fc8e42c67ab3f4680d8c348a92"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.2"]
